import { withBasePath } from '@/lib/basePath';

export const projects = [
  {
    id: 1,
    title: "Used Cars Price Prediction",
    slug: "used-cars-price-prediction",
    tags: ["Python", "Machine Learning", "XGBoost"],
    description: "End-to-end ML project predicting used car prices using ensemble methods and advanced regression techniques.",
    fullDescription: "A comprehensive machine learning project that analyzes used car datasets and builds predictive models. Implemented multiple algorithms including XGBoost, Random Forest, Gradient Boosting, Decision Trees, and Bagging, with final model achieving R² of 0.93 using XGBoost. Includes data exploration, feature engineering, model comparison, and hyperparameter tuning.",
    technologies: ["Python", "scikit-learn", "XGBoost", "Pandas", "NumPy"],
    models: ["XGBoost", "Random Forest", "Gradient Boosting", "Decision Tree", "Bagging", "AdaBoost", "Linear Regression"],
    results: {
      metric: "R² Score",
      bestModel: "XGBoost",
      value: "0.93",
    },
    link: "https://github.com/danielcp26/ML_Projects",
    image: withBasePath("/projects/project-1.jpg"),
    period: "2024",
    category: "Machine Learning",
  },
  {
    id: 2,
    title: "Boston House Price Prediction",
    slug: "boston-house-price-prediction",
    tags: ["Python", "Regression", "Analytics"],
    description: "Comparative regression analysis on the Boston housing dataset exploring multiple regression approaches.",
    fullDescription: "A detailed regression study comparing Linear Regression, Lasso, and Ridge regression on the Boston housing dataset. Includes EDA, feature analysis, model evaluation, and performance comparison. Achieved R² of 0.76 with thorough documentation of methodology and results interpretation.",
    technologies: ["Python", "scikit-learn", "Pandas", "Matplotlib", "Seaborn"],
    models: ["Linear Regression", "Lasso", "Ridge"],
    results: {
      metric: "R² Score",
      bestModel: "Linear Regression",
      value: "0.76",
    },
    link: "https://github.com/danielcp26/MIT_Data_Science_Projects",
    image: withBasePath("/projects/project-2.jpg"),
    period: "2024",
    category: "Data Analysis",
  },
  {
    id: 3,
    title: "Nashville Housing Data Cleaning",
    slug: "nashville-housing-data-cleaning",
    tags: ["SQL", "PostgreSQL", "Data Engineering"],
    description: "Advanced SQL data cleaning using CTEs, window functions, and string manipulation for large housing datasets.",
    fullDescription: "A production-grade SQL project demonstrating advanced data cleaning techniques on Nashville housing data. Utilizes CTEs, SPLIT_PART function for data parsing, CASE WHEN for conditional transformations, and ROW_NUMBER for deduplication. Standardizes address formats, manages null values, and creates clean datasets ready for analysis.",
    technologies: ["PostgreSQL", "SQL", "Window Functions", "CTEs"],
    techniques: ["CTEs", "SPLIT_PART", "CASE WHEN", "ROW_NUMBER", "String Manipulation", "Null Handling"],
    results: {
      metric: "Data Rows Cleaned",
      description: "Processed and standardized complete Nashville housing dataset",
    },
    link: "https://github.com/danielcp26/SQL_Projects",
    image: withBasePath("/projects/project-3.jpg"),
    period: "2023",
    category: "Data Engineering",
  },
  {
    id: 4,
    title: "Customer Segmentation Analysis",
    slug: "customer-segmentation-analysis",
    tags: ["Python", "Clustering", "K-Means"],
    description: "Unsupervised ML project segmenting customers based on behavior patterns using clustering algorithms.",
    fullDescription: "Customer segmentation project using K-Means clustering to identify distinct customer groups based on purchasing behavior, demographics, and engagement metrics. Includes RFM analysis, silhouette scoring for optimal cluster selection, and actionable business insights for targeted marketing strategies.",
    technologies: ["Python", "scikit-learn", "Pandas", "Matplotlib", "Seaborn"],
    models: ["K-Means", "Hierarchical Clustering", "DBSCAN"],
    results: {
      metric: "Silhouette Score",
      bestModel: "K-Means",
      value: "0.68",
    },
    link: "https://github.com/danielcp26/ML_Projects",
    image: withBasePath("/projects/project-4.jpg"),
    period: "2024",
    category: "Machine Learning",
  },
  {
    id: 5,
    title: "Sales Dashboard Power BI",
    slug: "sales-dashboard-powerbi",
    tags: ["Power BI", "DAX", "Analytics"],
    description: "Interactive sales analytics dashboard with KPIs, trends, and drill-down capabilities for business insights.",
    fullDescription: "Comprehensive Power BI dashboard providing real-time sales analytics, revenue tracking, and performance metrics. Features include YoY comparisons, regional breakdowns, product category analysis, and forecasting. Built with advanced DAX measures and optimized data models for fast performance.",
    technologies: ["Power BI", "DAX", "Power Query", "SQL"],
    results: {
      metric: "Reports Replaced",
      value: "15+",
    },
    link: "https://github.com/danielcp26/PowerBI_Projects",
    image: withBasePath("/projects/project-5.jpg"),
    period: "2024",
    category: "Business Intelligence",
  },
  {
    id: 6,
    title: "Churn Prediction Model",
    slug: "churn-prediction-model",
    tags: ["Python", "Classification", "Random Forest"],
    description: "Predictive model identifying at-risk customers using classification algorithms and feature importance analysis.",
    fullDescription: "End-to-end churn prediction project using Random Forest and Logistic Regression to identify customers likely to churn. Includes SMOTE for imbalanced data handling, feature importance analysis, ROC-AUC evaluation, and deployment-ready model pipeline. Achieved 87% accuracy with actionable retention insights.",
    technologies: ["Python", "scikit-learn", "imbalanced-learn", "Pandas"],
    models: ["Random Forest", "Logistic Regression", "XGBoost"],
    results: {
      metric: "Accuracy",
      bestModel: "Random Forest",
      value: "0.87",
    },
    link: "https://github.com/danielcp26/ML_Projects",
    image: withBasePath("/projects/project-6.jpg"),
    period: "2024",
    category: "Machine Learning",
  },
  {
    id: 7,
    title: "Olympic Medals Analysis",
    slug: "olympic-medals-analysis",
    tags: ["Python", "EDA", "Visualization"],
    description: "Exploratory data analysis of historical Olympic data revealing trends, patterns, and country performance insights.",
    fullDescription: "Comprehensive EDA project analyzing 120+ years of Olympic Games data. Explores medal distributions by country, gender disparities over time, sport popularity trends, and host country advantages. Features interactive visualizations and statistical insights using Python data science stack.",
    technologies: ["Python", "Pandas", "Matplotlib", "Seaborn", "Plotly"],
    results: {
      metric: "Years Analyzed",
      value: "120+",
    },
    link: "https://github.com/danielcp26/Data_Analysis_Projects",
    image: withBasePath("/projects/project-7.jpg"),
    period: "2024",
    category: "Data Analysis",
  },
  {
    id: 8,
    title: "Tableau Sales Visualization",
    slug: "tableau-sales-visualization",
    tags: ["Tableau", "Data Viz", "Analytics"],
    description: "Interactive Tableau dashboard showcasing sales performance with geographic mapping and trend analysis.",
    fullDescription: "Dynamic Tableau visualization project presenting multi-dimensional sales data analysis. Includes geographic heat maps, time series trending, category comparisons, and executive summary KPIs. Optimized for stakeholder presentations with clean design and intuitive drill-down navigation.",
    technologies: ["Tableau", "SQL", "Excel"],
    results: {
      metric: "Dashboards Created",
      value: "5",
    },
    link: "https://github.com/danielcp26/Tableau_Projects",
    image: withBasePath("/projects/project-8.jpg"),
    period: "2024",
    category: "Data Visualization",
  },
  {
    id: 9,
    title: "PISA Education Analysis",
    slug: "pisa-education-analysis",
    tags: ["Python", "Statistics", "Education"],
    description: "Statistical analysis of PISA reading scores examining factors affecting educational outcomes globally.",
    fullDescription: "In-depth statistical analysis of Programme for International Student Assessment (PISA) data. Investigates correlations between socioeconomic factors, school resources, and student performance across countries. Includes hypothesis testing, regression analysis, and policy-relevant findings for education improvement.",
    technologies: ["Python", "Pandas", "SciPy", "Statsmodels", "Matplotlib"],
    results: {
      metric: "Countries Analyzed",
      value: "70+",
    },
    link: "https://github.com/danielcp26/Data_Analysis_Projects",
    image: withBasePath("/projects/project-9.jpg"),
    period: "2024",
    category: "Data Analysis",
  },
  {
    id: 10,
    title: "COVID-19 Data Exploration",
    slug: "covid19-data-exploration",
    tags: ["SQL", "Analysis", "Healthcare"],
    description: "SQL-based exploration of global COVID-19 data analyzing infection rates, mortality, and vaccination progress.",
    fullDescription: "Comprehensive SQL project analyzing COVID-19 pandemic data across countries and time periods. Features include rolling averages, death rate calculations, vaccination coverage analysis, and comparative country studies. Demonstrates advanced SQL techniques including window functions, CTEs, and temp tables for large dataset handling.",
    technologies: ["SQL", "PostgreSQL", "Excel"],
    techniques: ["Window Functions", "CTEs", "Temp Tables", "Aggregations"],
    results: {
      metric: "Countries Tracked",
      value: "200+",
    },
    link: "https://github.com/danielcp26/SQL_Projects",
    image: withBasePath("/projects/project-10.jpg"),
    period: "2023",
    category: "Data Engineering",
  },
];
